### PR TITLE
fix double quotation marks is invalid in dfsioe

### PR DESCRIPTION
**Pull request by han-wang**

### CODE REVIEW

**Comment by carsonwang** [comment]
Hi @han-wang , why do we need a `\` before `"`?
The scripts work for me even without this patch. Do you encounter any problem?

**Comment by han-wang** [comment]
$MAP_JAVA_OPTS isn't set success

**Comment by carsonwang** [comment]
Thanks for the explanation, @han-wang . This works!
I noticed anther issue. It seems the  MAP_JAVA_OPTS is not probed correctly from mapred-site.xml?

**Comment by han-wang** [comment]
yes, the default is from mapred-site.xml, but we can't update mapred-site.xml  at on line, i need to be in the client incoming parameters.
error message :
16/04/22 14:23:23 INFO mapreduce.Job: Task Id : attempt_1461291374210_0055_m_000025_1, Status : FAILED
Container [pid=20472,containerID=container_e80_1461291374210_0055_01_000077] is running beyond virtual memory limits. Current usage: 120.9 MB of 2 GB physical memory used; 17.0 GB of 4.2 GB virtual memory used. Killing container.

**Comment by carsonwang** [comment]
OK. I'll merge this first. We can fix the other issue later in another PR. Thanks for the fix, @han-wang !

**Pull request merged**
