### PR TITLE
Fix the bug that dict path is not default.

### PR DESCRIPTION
**Pull request by pipamc**
Fix the bug that dict path is not default.

### CODE REVIEW

**Comment by GraceH** [comment]
@lvsoft , please help to check this PR.

**Comment by lvsoft** [comment]
It's pretty outdated, and as I remembered, in etl-recomm branch, there's a more completed support on dict related handling.

**Comment by lvsoft** [comment]
This PR is outdated. However, we do encounter similar issues in HiBench4.0, especially for some distributions lack the file `/usr/share/dict/words`, which will eventually affair all workloads( wordcount, sort, bayes) processing data generated by RandomTextWriter. I do think this PR is valuable and I'll try to merge into HiBench4.0 manually.

**Comment by carsonwang** [comment]
Can you please rebase this again the master branch? Otherwise I'll close it as this is really outdated.

**Pull request closed without merging**
