### PR TITLE
Set spark.sql.shuffle.partitions  to ${hibench.default.shuffle.parallelism}

### PR DESCRIPTION
**Pull request by gczsjdy**

### CODE REVIEW

**Comment by carsonwang** [comment]
retest this please

**Comment by carsonwang** [comment]
@gczsjdy , can you please update the title and submit a new commit to trigger the test?

**Comment by gczsjdy** [comment]
@carsonwang Check passed~

**Comment by carsonwang** [comment]
Merged. Thanks!

**Pull request merged**
