### PR TITLE
Reset Bayes Data Scale

### PR DESCRIPTION
**Pull request by ynXiang**
I reset Bayes data scale. The old scale for bigdata set is too large, and it will stuck for hadoop job. Now, when num. of pages is 30000, num. of classes is 10, and ngrams is 2, it costs about 35mins to finish the hadoop job. Therefore, bayes data scale is reset for reasonable time costs. Moreover, zoom is changed from 0.1 to 1 in order to run jobs with smaller num. of pages.

### CODE REVIEW

**Comment by carsonwang** [comment]
Can you please share your cluster information and all your configuration?
What is the data size of the generated data after your change?
How long does it take to run the workload (instead of datagen) for big data scale (both spark and hadoop)?

**Comment by ynXiang** [comment]
cluster information: 7 nodes
hibench.spark.master   yarn-client
hibench.yarn.executor.num     98
hibench.yarn.executor.cores   5
spark.executor.memory  15g
spark.driver.memory    4g
hibench.default.map.parallelism         490
hibench.default.shuffle.parallelism     490

data size:
hibench.bayes.tiny.pages                        10000
hibench.bayes.tiny.classes                      10
hibench.bayes.tiny.ngrams                       1
hibench.bayes.small.pages                       15000
hibench.bayes.small.classes                     10
hibench.bayes.small.ngrams                      1
hibench.bayes.large.pages                       20000
hibench.bayes.large.classes                     10
hibench.bayes.large.ngrams                      1
hibench.bayes.huge.pages                        25000
hibench.bayes.huge.classes                      10
hibench.bayes.huge.ngrams                       1
hibench.bayes.gigantic.pages                    30000
hibench.bayes.gigantic.classes                  100
hibench.bayes.gigantic.ngrams                   2
hibench.bayes.bigdata.pages                     35000
hibench.bayes.bigdata.classes                   100
hibench.bayes.bigdata.ngrams                    2

To bigdata data size of bayes:
prepare job needs 4mins
spark job needs 2mins
hadoop job needs 33mins
Actually, both prepare and spark jobs cost little time to be finished with different data size. To hadoop job, when ngrams is 1, it takes about 25mins; when ngrams is 2, it takes about 35mins. The time cost is increased if pages is increased.

Furthermore, when pages is very large, the hadoop job fails at "seq2sparse", which is the reason that I decrease pages in each data size.

**Comment by carsonwang** [comment]
I was actually asking for the data size on HDFS, how many GBs are generated for the big data scale?
It looks like the updated size is too small for Spark. It is common for our users running HiBench on a 20 nodes' cluster. The new big data profile will be a very small size for them. 

Did you run the original big data scale on Spark and how long did it take?
What is the real cause of the hadoop job failure? Can we tune some parameters like parallelism to workaround it?

**Comment by chenghao-intel** [comment]
Agree with @carsonwang , I don't think we should update the scale number, probably in the future, we need to give the example parameters for typical cluster settings like 10 nodes cluster with certain CPU / DISK / Network etc.

I think we need to put this into account for next HiBench release.

**Pull request closed without merging**
