### PR TITLE
[SMALLFIX] Drop buffer cache after writing preparing the input

### PR DESCRIPTION
**Pull request by peisun1115**
Drop the buffer cache after preparing the data to better simulate the real production env.

### CODE REVIEW

**Comment by carsonwang** [comment]
Thanks for the PR. Dropping the buffer cache before each run is always a good practice. 
It seems this only works for Spark standalone mode but doesn't work for running on Yarn. Because when running Spark on Yarn, the slaves file in spark can be empty.

**Comment by peisun1115** [comment]
@carsonwang  I've never used yarn. I don't know how to get the slaves when running it on yarn now.  I will figure it out. Let me know if you have an answer. 

btw i updated the PR to get slaves from hadoop home since what we want is to clear the buffer cache on hdfs workers.

**Comment by carsonwang** [comment]
This doesn't work for the default configuration. There are multiple occurrences of `hibench.hadoop.home` in  99-user_defined_properties.conf. The `HADOOP_HOME` got from it is `${hibench.hadoop.home}/bin-mapreduce1/hadoop` which is not correct.

**Comment by carsonwang** [comment]
Hi peisun1115, we'd like to include this in HiBench 6.0. Do you have time to update this?
A better way to get the slaves is to use bin/functions/load_config.py. After that, you can use the variable `SLAVES` directly in the script. You can refer to the workload run script. i.e. `bin/workload/micro/wordcount/spark/run.sh`. After `enter_bench` is called, all the configurations are parsed and `SLAVES` is set.

**Comment by peisun1115** [comment]
@carsonwang I don't have time to update this. Given that you are very clear about how to use load_config.py, could you just patch my PR or just open a new one and fix it with what you suggested? thanks. I will close this PR.

**Pull request closed without merging**
