### PR TITLE
Support Multiple runs for scan/join/aggregation workloads

### PR DESCRIPTION
**Pull request by nareshgundla**

### CODE REVIEW

**Comment by carsonwang** [comment]
Hi @nareshgundla , is this for fixing the same value of Throught and Throught/node in the hibench.report? This is likely caused by a miss configuration. The current script has logic in `bin/functions/load-config.py` to get the slave nodes.

**Comment by nareshgundla** [comment]
Hi @carsonwang  yes that was for fixing the same value of throughput and throughput/node in the hibench.report. 
one more commit was to fix the issue for multiple runs for (scan/aggregation/join) workloads in hibench.

I have checked the logic in bin/functions/load-config.py, in that for spark-master (yarn-client) it is using the wrong path for yarn executable (/usr/lib/hadoop/bin/yarn) but actual path in cloudera clusters is /usr/bin/yarn

**Comment by carsonwang** [comment]
Yes. For cdh, `hibench.hadoop.executable ` has to be configured to make it work.

**Comment by carsonwang** [comment]
Were you using an external meta store when running the (scan/aggregation/join)  workloads?

**Comment by nareshgundla** [comment]
what will be the exact value for hibench.hadoop.executable in CDH environment ??
[/usr/lib/hadoop/bin/hadoop or ??]

No we are not using any external meta store,
that commit is just to fix issue #143 for default CDH installations.

**Comment by carsonwang** [comment]
It should be /usr/bin/hadoop if hadoop and yarn are located in /usr/bin/ directory in your environment. HiBench doesn't do well to auto detect the path for CDH so this has to be configured. Once this is configured correctly, the throughput should be  correct. 

Thanks for fixing issue #143. Can you update the PR and I'll merge the fix?

**Comment by nareshgundla** [comment]
reverted back the changes done for Throughput correction for nodes

Updated the PR as related to issue #143

**Comment by carsonwang** [comment]
Thanks @nareshgundla !

**Pull request merged**
