### PR TITLE
Docker for HiBench

### PR DESCRIPTION
**Pull request by princhenee**
Rudimentary version for HiBench, especially for v-4.0

### CODE REVIEW

**Comment by GraceH** [comment]
@lvsoft @GayathriMurali

**Comment by GraceH** [comment]
In general, why we introduced such kind of util. 
 * To quickly setup test environment for different Spark/hadoop version.
 * To help the end user (E.g., CDH user) to understand how to configure and run hibench properly.

**Comment by GraceH** [comment]
For those users who want to try HiBench with ease, they can run docker file to get a quick and simple deployment.

**Comment by lvsoft** [comment]
@princhenee can you rebase to current v4.0 branch and update your PR? There's some important bug fixes after you submitted this PR. Thanks.

**Comment by GraceH** [comment]
@lvsoft  Since it is mostly the deployment related work, and not change any benchmark or configuration content in HiBench. it may not bring any conflict, Am I right?

**Comment by lvsoft** [comment]
@GraceH however, its content is based on previous HiBench-4.0 branch, which has a bug(a137c20f6261266094fba7fed6900b661ecf5c07)  related to hostname and may stop to run if the hostname contains any one character in "s,p,a,r,k". So I highly suggests to make a rebase before merge.

**Comment by GraceH** [comment]
There is not any conflict so far. The only thing might need to change is the HIBENCH_VERSION. Am I right?

**Comment by princhenee** [comment]
@lvsoft  I have rebased to the current v4.0-branch, please check if it is ok.

**Pull request merged**
