### PR TITLE
Spark 2.0.0 support

### PR DESCRIPTION
**Pull request by a-roberts**
In this PR I've changed a few methods so that we can compile and run successfully with Spark 2.0, I've created this pull request so everyone can see the changes I have made and we can work together to get this contributed

Here are the known problems we should resolve
1) Streambench - lots of changes and I need to figure out which are neccessary, I didn't want to touch this at all
2) I build with mvn -T 1C package -D spark2.0 from the sparkbench directory containing the pom.xml, run-all.sh no longer works correctly
3) presumably we want a new HiBench release: 6 instead of 5 snapshot (I think moving up a Spark major version is definitely sufficient of a new HIBench release)
4) we think there's a performance problem in at least one place (ordering in ScalaTeraSort) so that line of code is likely to change, I'm also concerned about my other changes so looking for a code review, currently we consistently see Spark 2.0 with this benchmark performing slower than Spark 1.x
5) conf/99-user_defined_properties.conf.template has the Spark version now being 2.0 instead of 1.6
6) I have kafka provided and a newer version is specified, do we want this?
7) we were previously looking in the sonatype repository for jars no longer present and so I added the mvn central repository lookup

Also, do we want to create a new branch? 

How should we handle the multiple Scala versions (you'll see here I set the scala version to be 2.11.8 but presumably we'd still want 2.10.5 for 1.x)

### CODE REVIEW

**Comment by chenghao-intel** [comment]
thank you @a-roberts for working on this, I am thinking if we need to support different versions of Spark. But for now, probably we'd better create another branch for the Spark 2.0 support, what do you think?

**Comment by chenghao-intel** [comment]
And actually, we are thinking to simplify the build process, since most of the workloads are quite independent, and we can let the user to build each specified workloads by passing the workload names and some other per workload options.

So that we can naturally avoid the dependent jars conflict among the whole project. Let me know if you wants to join the discussion.

**Comment by a-roberts** [comment]
Thanks for the quick feedback, I agree we should create a new branch for this and I think we should maintain both branches (so we can either use 1.x and 2.x or provide more granularity e.g. 1.4.x, 1.5.x, 1.6.x, etc) for the following reasons

- I think the 1.x API unlikely to change and people will still be using it - thinking about existing workloads out there and people that don't want to migrate their application just yet
- by supporting both we can provide a ballpark figure comparison between major releases
- mailing list discussions suggest the 1.x line will continue to be maintained for the foreseeable future

I can join the discussion on simplifying the process, my initial thought is that we could refactor this project to be built the Spark way, so individual benchmarks would be profiles and we'd specify a Spark and Scala version here (just like for Spark we can specify the Scala version)

An example command could be something like this from the top level directory...what do you think is ideal for our users and is there an issue open where we can discuss this on a separate topic?
```
mvn -Pstreambench -Psparkbench -Dspark-version=2.0 package -Dscala.version=2.11
```
and then to run a benchmark we could use the existing shell script

I now have an idea of why the ordering problem exists and potentially why performance appears worse compared to 1.x, referencing my colleague in IBM Andrew Craik's input:

"The change to ordering here changed behaviour, the previous implementation was relying on an implicit conversion in SparkContext that was deprecated that allowed a Array[Byte] to be silently wrapped in a Hadoop WriteableBytes which had a compareTo operator. The second issue is in the BaseRangePartitioner, there are two fields in the constructor partitions and RDD, they were declared as
```
@transient partitions: Int,
@transient rdd: RDD ... 
```
which worked in 2.10 but there is a scalac bug which means that the @transient is dropped and so those fields get serialized when compiled with 2.11 , the fix is to put in the implicit private val so we do 

```
@transient private val partitions
```
and that makes the fields be marked as transient and ignored by the serializer"

I'll update this pull request shortly with said changes

**Comment by mwws** [comment]
@a-roberts We are planning a big project structure refactoring. which may happen at the Middle of Sep.  The detail plan will be sent out in next couple of weeks for farther discussion. And I would like to keep this PR pending for now.

For your questions:
(1) We would support better streaming benchmark next in next release version , and also streaming part would be decoupled with SQL benchmark.
(2) Definitely, It will be great if we can support Spark 2.0 in next release. Much thanks for your work.
(6) I think updating Kafka to 8.2.2 is reasonable.

**Comment by TiagoPerez** [comment]
Hi Robert, great work with HiBench and Spark-Perf... Ever though of doing something similar for SparkBench? https://github.com/SparkTC/spark-bench

**Comment by a-roberts** [comment]
Hi, any update here please?

@TiagoPerez I've contacted the authors, I agree it would be useful for SparkBench to support Spark 2.0 also, I don't know enough about how SparkBench works just yet

**Comment by carsonwang** [comment]
We are working on the project refactoring which is part of 6.0. I'll start a new thread for better discussing the changes in 6.0. When this is done, it will be great to add Spark 2.0 support to it.

**Comment by carsonwang** [comment]
Hi @a-roberts ,  we have a WIP branch 6.0. I described the changed we are going to make in HiBench 6.0 at #330.  More workloads will be added back soon. 
Would you mind porting this PR to branch 6.0? 
We can now build it using `mvn -Dspark=2.0 clean package`.  Currently this fails because of the TeraSort workload issue as you mentioned above.

**Comment by carsonwang** [comment]
I submitted #337 to port some changes to the 6.0 branch. If you have a PR ready to the 6.0 branch. Please feel free to submit it. Thanks!

**Comment by a-roberts** [comment]
Closing based on Carson's merge referenced above, #337, cheers

**Pull request closed without merging**
