### PR TITLE
Fix for java.lang.IllegalArgumentException : Wrong FS

### PR DESCRIPTION
**Pull request by viplav**
The Configuration object used to get the FileSystem object was set in
the Map Task constructor. But at constructor time, the configuration
object points to the default configuration, not the actual configuration
used by the job (i.e. when the job is submitted).  This configuration
could be different from the default configuration and is specified in
the job.xml file  for the job.  The actual configuration is sent by the
MapRunner using callback for configure method and should be used to get
the actual job configuration.

### CODE REVIEW

**Comment by viplav** [comment]
I have sent this pull request ( https://github.com/intel-hadoop/HiBench/pull/110 ) to fix the issue with using wrong FS resulting in errors like  "Mkdirs failed to create" etc. Please take a look and merge so that people who run into this issue (e.g. using Hortonworks HDP 2) will benefit. Issues #27 and #80 will be fixed by this PR.

**Comment by adrian-wang** [comment]
@lvsoft  Can you verify this patch?

**Comment by viplav** [comment]
Thanks @adrian-wang and @lvsoft . Just wanted to mention that I tested the fix on HDP 2.2.4, CDH 5.3 and Apache 2.7.0

**Comment by adrian-wang** [comment]
I'm merging this, thanks!
Closes #27 .
Closes #80 .

**Comment by viplav** [comment]
Thanks @adrian-wang

**Comment by naveenmadhire** [comment]
I am getting the Same error again while running Dfsio. However the wordcount, scan, sleep are working fine. 
Is there any workaround for this?

java.lang.IllegalArgumentException: Wrong FS:

**Pull request merged**
