### PR TITLE
Add HDP support

### PR DESCRIPTION
**Pull request by jerryshao**
This PR adds the HiBench support for HDP, there's little difference for HDP, so here are the changes:

1. Add a new configuration `hibench.hadoop.mapreduce.home`, default is equal to `hibench.hadoop.home`, for HDP it is a different directory, so user has to configure this.
2. Hadoop release auto probing mechanism is failed for HDP, since it has the same output as Apache Hadoop to use `hadoop version | head -1 | cut -d \  -f 2`, so for HDP `hibench.hadoop.release` should be specified explicitly, unless we improve the probing mechanism.

Please help to review @lvsoft @GraceH , thanks a lot.

### CODE REVIEW

**Comment by GraceH** [comment]
@jerryshao In general, it looks good to me.  We are now introducing docker support for both CDH/apache version. That will be good if you can take a look at that PR for more distributions. So that we can prove the change by "single command". Your comments are warmly welcomed.

**Comment by GraceH** [comment]
here is the PR for docker support for your reference. https://github.com/intel-hadoop/HiBench/pull/130

**Comment by jerryshao** [comment]
I'm afraid I'm not familiar with Docker, from my first glance, it still needs to distinguish Apache Hadoop, CDH or something else, though maybe the script is quite similar. 

I will try to understand #130 , hopes it can also support HDP, as I know many HDP customers they're using HiBench to do benchmark.

**Comment by GraceH** [comment]
Thanks @jerryshao. The original idea for docker PR #130 is the showcase for different distribution. It is quite related. And at same time, I will merge this if it has already verified by HDP users.

**Comment by GraceH** [comment]
BTW, we will have a minor release version soon. Hope this feature can be added before the release. :+1:

**Comment by jerryshao** [comment]
Thanks a lot @GraceH . Also please help to review if there's any missing corner where I forgot to address.

I've already verified terasort, wordcount, pagerank, aggregation, sleep. I assume other workloads can also be worked, though I'm not verified yet.

Besides, I think there's data skew problem in terasort, I guess the problem might lies in our customized range partitioner, would you please check again.

**Comment by jerryshao** [comment]
HP guys they tested terasort with Spark and MR, they found Spark is slower than MR, I think this problem might be due to data skewness.

**Comment by lvsoft** [comment]
Seems fine to me, I'll just merge it. Thanks @jerryshao, obviously you discover the configuration rules without any doc, which is not easy. Nice work.

**Comment by GraceH** [comment]
Thanks @jerryshao !

**Pull request merged**
